[tool.black]
line-length = 88  # The black default a good compromise.
target-version = ['py27', 'py37']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.md
  |\.txt
  |\.yml
  |\.ui
  |\.mel
)/
'''
