[package]
name = "mmscenegraph_rust"
version = "0.1.0"
authors = ["david-cattermole <cattermole91@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "mmscenegraph_rust"
path = "./src/lib.rs"
# NOTE: 'lib' is used to link with Rust crates, staticlib' is used to
# link with C++.
#crate_type = ["staticlib", "lib"]
# crate_type = ["cdylib", "lib"]
crate_type = ["lib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
# NOTE: If we use 'panic = "abort"' then we are unable to produce tests.
# # https://github.com/rust-lang/cargo/issues/6313
#
# panic = "abort"
debug-assertions = false
