name: Lint Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Analysing the Python code with flake8 (Warnings Only)
        run: |
          ./scripts/python_linter_run_flake8.bash

      - name: Analysing the C++ code with CppLint
        run: |
          ./scripts/python_linter_run_cpplint.bash

      - name: Analysing the Python code with flake8 (Hard Error)
        run: |
          ./scripts/python_linter_run_flake8_errors_only.bash

      - name: Check Python Formatting
        run: |
          ./scripts/python_formatter_run_black.bash

      - name: Install Clang-Format
        run: |
          sudo apt-get install -y clang-format

      - name: Check C++ Code with Clang-Format
        run: |
          sudo apt-get install -y clang-format clang-tidy
